language: android
os: linux
dist: trusty
jdk: openjdk11
android:
  components:
    - tools
    - android-30
    - build-tools-30.0.2

before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  - rm -Rf $HOME/.m2/repository/com/ibotta/gradle/aop/
  - ./publishLocal.sh
  - ./gradlew build

install: skip

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/